[package]
name = "dmx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_dmx = "0.3.3"
rand = "0.8.5"